robot_0: {
    battery_mockup/battery_autonomy: 200,
}
robot_1: {
    battery_mockup/battery_autonomy: 200,
}
robot_2: {
    battery_mockup/battery_autonomy: 200,
}
robot_3: {
    battery_mockup/battery_autonomy: 200,
}